# 🐍 Python Data Structures — Practice Worksheet
### 18 Tasks covering Numbers, Booleans, Strings, Loops, Lists, Tuples, Dictionaries, Sets, NumPy & Pandas

---

> 📌 **Instructions**
> - Complete **all 18 tasks** from top to bottom — each builds on previous concepts.
> - Fill in every `# YOUR CODE HERE` block. Do **not** change task descriptions.
> - Run each cell after completing it to verify your output.
> - Expected outputs are shown where helpful.

---


## ⚙️ Setup — Run This Cell First


In [1]:
import random
import collections
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
print("All libraries imported successfully ✅")


All libraries imported successfully ✅


---
# 🔢 Section 1 — Primitive Data Types


## 📝 Task 1 — Numbers & Arithmetic

### Background
Python supports two main numeric types: `int` (whole numbers) and `float` (decimals). You can use the standard arithmetic operators: `+`, `-`, `*`, `/`, `//` (floor division), `%` (modulo), `**` (exponentiation).

### 🎯 Your Task
Given `a = 17` and `b = 5`, compute and **print** each of the following with a descriptive label:

| Expression | Expected Output |
|---|---|
| `a + b` | 22 |
| `a - b` | 12 |
| `a * b` | 85 |
| `a / b` | 3.4 |
| `a // b` | 3 |
| `a % b` | 2 |
| `a ** b` | 1419857 |

Then print the **type** of `a` and the **type** of `a / b` and explain (in a comment) why they differ.

> 💡 **Hint:** Use `print(f"a + b = {a + b}")` for clean labelled output. Use `type()` to check types.


In [ ]:
a = 17
b = 5

# YOUR CODE HERE
# Print all 7 arithmetic results with labels
print(a+b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)
# Print type of a
print(type(a))

# Print type of a / b
print(type(a/b))

# Comment: why is the type of a/b different from the type of a?
# Answer:
# The type of a is integer and the type of a/b is float.

22
85
3.4
3
2
1419857
<class 'int'>
<class 'float'>


## 📝 Task 2 — Boolean Logic

### Background
Python's Boolean type has two values: `True` and `False`. Logical operators are written as English words: `and`, `or`, `not`. The XOR (exclusive or) result can be checked with `!=`.

### 🎯 Your Task
Given `p = True` and `q = False`:

1. Print the result of `p and q`, `p or q`, `not p`, and `p != q`
2. Create a variable `score = 73` and write an `if / elif / else` block that prints:
   - `"Distinction"` if score ≥ 85
   - `"Merit"` if score is between 70 and 84 (inclusive)
   - `"Pass"` if score is between 50 and 69 (inclusive)
   - `"Fail"` otherwise

> 💡 **Hint:** Use `elif` for multiple conditions. The order matters — check the highest threshold first.


In [6]:
p = True
q = False

# YOUR CODE HERE — Part 1: Boolean operations
print(p and q)
print(p or q)
print(not p)
print(p != q)

# YOUR CODE HERE — Part 2: Grade classifier
score = 73
if score >= 85:
 print("Distinction")
elif score >= 70 and score <= 80:
 print("merit")
elif score >= 50 and score <= 69:
 print("pass")
else:
 print("Fail")

False
True
False
True
merit


## 📝 Task 3 — String Operations

### Background
Strings in Python are sequences of characters. Useful built-in string methods include `.upper()`, `.lower()`, `.replace()`, `.split()`, `.strip()`, and `.count()`. You can also use `len()`, slicing `[start:end]`, and f-strings for formatting.

### 🎯 Your Task
Work with the sentence below and complete all five operations:

```python
sentence = "  Python is a powerful programming language  "
```

| # | Operation | Expected Result |
|---|-----------|-----------------|
| 1 | Strip whitespace | `"Python is a powerful programming language"` |
| 2 | Convert to UPPERCASE | `"PYTHON IS A POWERFUL PROGRAMMING LANGUAGE"` |
| 3 | Count the word `"a"` (exact, case-sensitive) | `1` |
| 4 | Replace `"powerful"` with `"versatile"` | `"Python is a versatile programming language"` |
| 5 | Split into a list of words | `['Python', 'is', 'a', 'versatile', ...]` |

Finally, use an **f-string** to print: `"The sentence has X words."` (where X is the actual count).

> 💡 **Hint:** Chain methods: `sentence.strip().upper()`. Use `.split()` with no arguments to split on any whitespace.


In [7]:
sentence = "  Python is a powerful programming language  "

# YOUR CODE HERE
# 1. Strip whitespace and save to 'clean'
clean = sentence.strip()
print(clean)
# 2. Print UPPERCASE version
print(clean.upper())

# 3. Count occurrences of the word "a"
count_a = clean.count("a")
print(count_a)

# 4. Replace "powerful" with "versatile" and save to 'new_sentence'
new_sentence = clean.replace("powerful", "versatile")
print(new_sentence)
# 5. Split new_sentence into a list of words
words = new_sentence.split()
print(words)
# Print: "The sentence has X words."
print(f"The sentence has {len(words)} words.")

Python is a powerful programming language
PYTHON IS A POWERFUL PROGRAMMING LANGUAGE
4
Python is a versatile programming language
['Python', 'is', 'a', 'versatile', 'programming', 'language']
The sentence has 6 words.


## 📝 Task 4 — Loops & Conditionals

### Background
`for` loops iterate over a sequence. `while` loops run as long as a condition is `True`. Use `break` to exit early and `continue` to skip to the next iteration.

### 🎯 Your Task

**Part A:** Use a `for` loop with `range()` to print all **even numbers from 1 to 30** on a single line separated by spaces.

**Part B:** Use a `while` loop to compute the **sum of all odd numbers from 1 to 99** (i.e., 1 + 3 + 5 + … + 99). Print the result.
> Expected answer: 2500

**Part C:** Use a `for` loop over `range(1, 21)`. Print the number normally, **but**:
- If divisible by both 3 and 5 → print `"FizzBuzz"`
- If divisible by 3 only → print `"Fizz"`
- If divisible by 5 only → print `"Buzz"`

> 💡 **Hint for Part A:** Use `print(n, end=' ')` to stay on the same line, or build a list and use `' '.join(...)`.  
> 💡 **Hint for Part C:** Check the combined condition (`% 3 == 0 and % 5 == 0`) **first** before the individual ones.


In [10]:
# Part A: Even numbers from 1 to 30
# YOUR CODE HERE

for num in range(1, 30):
    if num % 2 == 0:
        print(num, end=' ')
print()


# Part B: Sum of odd numbers from 1 to 99
# YOUR CODE HERE
total = 0
num = 1

while num <= 99:
    total += num
    num += 2  # Increment by 2 to get next odd number

print(total)  

# Alternative solution:
# total = 0
# num = 1
# while num <= 99:
#     if num % 2 == 1:  # Check if odd
#         total += num
#     num += 1
# print(total)


# Part C: FizzBuzz from 1 to 20
# YOUR CODE HERE
for num in range(1, 21):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz")
    elif num % 3 == 0:
        print("Fizz")
    elif num % 5 == 0:
        print("Buzz")
    else:
        print(num)

2 4 6 8 10 12 14 16 18 20 22 24 26 28 
2500
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


---
# 📋 Section 2 — Lists


## 📝 Task 5 — List Basics: Create, Access, Modify

### Background
A Python list is **mutable** and **ordered**. Elements are accessed by zero-based index. Negative indices count from the end (`-1` is the last element). Common methods: `.append()`, `.insert()`, `.remove()`, `.pop()`, `.sort()`, `.reverse()`.

### 🎯 Your Task
Start with:
```python
fruits = ["mango", "banana", "apple", "cherry", "orange"]
```

Perform the following operations **in order**, printing the list after each step:

1. Print the **first** and **last** element using positive and negative indexing.
2. **Append** `"grape"` to the end.
3. **Insert** `"kiwi"` at index 2.
4. **Remove** `"banana"` from the list.
5. **Pop** the element at index 0 and print what was removed.
6. **Sort** the list alphabetically and print it.
7. **Reverse** the sorted list and print it.

> 💡 **Hint:** Remember that `.pop(index)` returns the removed element, so you can capture it: `removed = fruits.pop(0)`.


In [12]:
fruits = ["mango", "banana", "apple", "cherry", "orange"]

# YOUR CODE HERE
# 1. Print first and last elements
print(f"First element (positive index): {fruits[0]}")
print(f"Last element (positive index): {fruits[4]}")
print(f"First element (negative index): {fruits[-5]}")
print(f"Last element (negative index): {fruits[-1]}")
print(f"Current list: {fruits}")
print("-" * 40)

# 2. Append "grape"
fruits.append("grape")
print(f"After appending 'grape': {fruits}")
print("-" * 40)

# 3. Insert "kiwi" at index 2
fruits.insert(2, "kiwi")
print(f"After inserting 'kiwi' at index 2: {fruits}")
print("-" * 40)

# 4. Remove "banana"
fruits.remove("banana")
print(f"After removing 'banana': {fruits}")
print("-" * 40)

# 5. Pop element at index 0, print what was removed
removed_item = fruits.pop(0)
print(f"Removed element: {removed_item}")
print(f"After popping index 0: {fruits}")
print("-" * 40)

# 6. Sort alphabetically
fruits.sort()
print(f"After sorting: {fruits}")
print("-" * 40)

# 7. Reverse the list
fruits.reverse()
print(f"After reversing: {fruits}")

First element (positive index): mango
Last element (positive index): orange
First element (negative index): mango
Last element (negative index): orange
Current list: ['mango', 'banana', 'apple', 'cherry', 'orange']
----------------------------------------
After appending 'grape': ['mango', 'banana', 'apple', 'cherry', 'orange', 'grape']
----------------------------------------
After inserting 'kiwi' at index 2: ['mango', 'banana', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
----------------------------------------
After removing 'banana': ['mango', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
----------------------------------------
Removed element: mango
After popping index 0: ['kiwi', 'apple', 'cherry', 'orange', 'grape']
----------------------------------------
After sorting: ['apple', 'cherry', 'grape', 'kiwi', 'orange']
----------------------------------------
After reversing: ['orange', 'kiwi', 'grape', 'cherry', 'apple']


## 📝 Task 6 — List Slicing

### Background
Slicing extracts a **sub-list** using the syntax `list[start:stop:step]`:
- `start` is inclusive, `stop` is exclusive
- A negative `step` reverses the direction
- Omitting `start` or `stop` defaults to the beginning or end

### 🎯 Your Task
Work with:
```python
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

| # | Slice | Expected Result |
|---|-------|-----------------|
| 1 | First 4 elements | `[0, 1, 2, 3]` |
| 2 | Last 3 elements | `[7, 8, 9]` |
| 3 | Elements from index 2 to 7 | `[2, 3, 4, 5, 6]` |
| 4 | Every second element | `[0, 2, 4, 6, 8]` |
| 5 | The entire list **reversed** | `[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]` |
| 6 | Last 5 elements **reversed** | `[9, 8, 7, 6, 5]` |

> 💡 **Hint:** To reverse use `[::-1]`. For last N items use `[-N:]`. To reverse a slice: `numbers[4:9][::-1]` reverses a sub-section.


In [1]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# YOUR CODE HERE
# 1. First 4 elements
first_four = numbers[0:4]  # or simply numbers[:4]
print(f"First 4 elements: {first_four}")

# 2. Last 3 elements
last_three = numbers[-3:]  # starts from index -3 (7) to the end
print(f"Last 3 elements: {last_three}")

# 3. Index 2 to 7 (not including 7)
index_2_to_7 = numbers[2:7]  # includes 2,3,4,5,6 (7 is exclusive)
print(f"Elements from index 2 to 7: {index_2_to_7}")

# 4. Every second element
every_second = numbers[::2]  # start:beginning, stop:end, step:2
print(f"Every second element: {every_second}")

# 5. Entire list reversed
reversed_all = numbers[::-1]  # step -1 reverses the entire list
print(f"Entire list reversed: {reversed_all}")

# 6. Last 5 elements reversed
last_five_reversed = numbers[-5:][::-1]  # two-step approach
# Alternative: numbers[:4:-1] - but the two-step approach is clearer
print(f"Last 5 elements reversed: {last_five_reversed}")

First 4 elements: [0, 1, 2, 3]
Last 3 elements: [7, 8, 9]
Elements from index 2 to 7: [2, 3, 4, 5, 6]
Every second element: [0, 2, 4, 6, 8]
Entire list reversed: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Last 5 elements reversed: [9, 8, 7, 6, 5]


## 📝 Task 7 — List Comprehensions

### Background
List comprehensions are a concise way to create lists:
```python
[expression for item in iterable if condition]
```
They replace many `for` loops with a single readable line.

### 🎯 Your Task
Use **list comprehensions** (no regular for-loops!) to create and print each of the following:

1. A list of the **squares** of numbers 1 through 15: `[1, 4, 9, 16, ...]`
2. A list of numbers from 1–50 that are **divisible by 3 or 5** (but not both): `[3, 5, 6, 9, 10, ...]`
3. A list of the **lengths** of each word in the sentence `"the quick brown fox jumps over the lazy dog"`
4. A list of **uppercase versions** of only the words that have **5 or more letters**: `['QUICK', 'BROWN', 'JUMPS', 'LAZY']` *(hint: 'over' has 4, skip it)*

> 💡 **Hint for #2:** `(n % 3 == 0) != (n % 5 == 0)` is Python's way to express XOR for two conditions.  
> 💡 **Hint for #3:** `sentence.split()` gives you the word list.


In [2]:
# 1. Squares of 1 to 15
print([x**2 for x in range(1, 16)])

# 2. Numbers 1-50 divisible by 3 OR 5 but NOT both
print([n for n in range(1, 51) if (n % 3 == 0) != (n % 5 == 0)])

# 3. Lengths of each word in the sentence
sentence = "the quick brown fox jumps over the lazy dog"
print([len(word) for word in sentence.split()])

# 4. Uppercase words with 5 or more letters
print([word.upper() for word in sentence.split() if len(word) >= 5])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]
[3, 5, 6, 9, 10, 12, 18, 20, 21, 24, 25, 27, 33, 35, 36, 39, 40, 42, 48, 50]
[3, 5, 5, 3, 5, 4, 3, 4, 3]
['QUICK', 'BROWN', 'JUMPS']


## 📝 Task 8 — Nested Lists & the `collections.Counter`

### Background
A **list of lists** creates a 2D (matrix-like) structure. Access elements with `matrix[row][col]`.  
`collections.Counter` is a dictionary subclass that counts how many times each element appears in an iterable.

### 🎯 Your Task

**Part A — Nested List:**  
Create the following 3×3 matrix as a list of lists and then:
```
matrix = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
```
- Print the **second row** (index 1)
- Print the **element at row 2, column 1** (value: 8)
- Use a nested list comprehension to create a **transposed** version (rows become columns)
  - Expected: `[[1, 4, 7], [2, 5, 8], [3, 6, 9]]`

**Part B — Counter:**  
Generate a list of 300 random integers between 1 and 10 (inclusive), then:
- Use `collections.Counter` to count each number
- Print the **3 most common** numbers and their counts
- Print the **least common** number

> 💡 **Hint for transpose:** `[[matrix[r][c] for r in range(3)] for c in range(3)]`  
> 💡 **Hint for Counter:** `counter.most_common(3)` returns the top 3 as a list of `(value, count)` tuples.


In [3]:
import collections, random

# Part A — Nested list
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# Print second row
print("Second row:", matrix[1])

# Print element at row 2, col 1
print("Element at row 2, col 1:", matrix[2][1])

# Transpose using nested list comprehension
transposed = [[matrix[r][c] for r in range(3)] for c in range(3)]
print("Transposed matrix:", transposed)

# Part B — Counter
random.seed(42)

# Generate 300 random integers between 1 and 10
random_numbers = [random.randint(1, 10) for _ in range(300)]

# Count with Counter
counter = collections.Counter(random_numbers)

# Print top 3 most common
print("Top 3 most common:", counter.most_common(3))

# Print least common
# Find the minimum count value among all numbers
min_count = min(counter.values())
# Get all numbers with that minimum count
least_common = [num for num, count in counter.items() if count == min_count]
print("Least common number(s):", least_common)

Second row: [4, 5, 6]
Element at row 2, col 1: 8
Transposed matrix: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Top 3 most common: [(4, 42), (2, 40), (9, 35)]
Least common number(s): [6]


---
# 🔒 Section 3 — Tuples


## 📝 Task 9 — Tuples: Immutability & Practical Uses

### Background
Tuples look like lists but use `()` instead of `[]`. They are **immutable** — you cannot add, remove, or change elements after creation. This makes them useful for fixed data like coordinates, RGB colours, or records. Tuples support indexing, slicing, and iteration just like lists.

### 🎯 Your Task

**Part A — Basic Tuple Operations:**
```python
student = ("Alice", 22, "Computer Science", 3.8)
```
- Print the student's name (index 0) and GPA (index 3)
- Try to change the name to `"Bob"` — catch the resulting `TypeError` with a `try/except` block and print `"Tuples are immutable!"`
- Unpack the tuple into 4 separate variables: `name, age, major, gpa` and print each

**Part B — List of Tuples:**  
You have coordinates of 5 cities:
```python
cities = [("Karachi", 24.86, 67.01),
          ("Lahore",  31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar", 34.01, 71.57),
          ("Quetta",  30.18, 66.99)]
```
- Loop over the list and print each city in the format: `"City: Karachi | Lat: 24.86 | Lon: 67.01"`
- Sort the cities by **latitude** (ascending) and print the sorted list

> 💡 **Hint for sorting:** `sorted(cities, key=lambda c: c[1])` sorts by the second element of each tuple.


In [4]:
# Part A
student = ("Alice", 22, "Computer Science", 3.8)

# Print name and GPA
print("Name:", student[0])
print("GPA:", student[3])

# Try to change name — catch TypeError
try:
    student[0] = "Bob"
except TypeError:
    print("Tuples are immutable!")

# Unpack into 4 variables and print each
name, age, major, gpa = student
print(f"Name: {name}, Age: {age}, Major: {major}, GPA: {gpa}")


# Part B
cities = [("Karachi",   24.86, 67.01),
          ("Lahore",    31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar",  34.01, 71.57),
          ("Quetta",    30.18, 66.99)]

# Loop and print each city's info
for city in cities:
    print(f"City: {city[0]} | Lat: {city[1]} | Lon: {city[2]}")

# Sort by latitude and print
cities_sorted = sorted(cities, key=lambda c: c[1])
print("\nCities sorted by latitude (ascending):")
for city in cities_sorted:
    print(f"{city[0]}: {city[1]}")

Name: Alice
GPA: 3.8
Tuples are immutable!
Name: Alice, Age: 22, Major: Computer Science, GPA: 3.8
City: Karachi | Lat: 24.86 | Lon: 67.01
City: Lahore | Lat: 31.55 | Lon: 74.35
City: Islamabad | Lat: 33.72 | Lon: 73.06
City: Peshawar | Lat: 34.01 | Lon: 71.57
City: Quetta | Lat: 30.18 | Lon: 66.99

Cities sorted by latitude (ascending):
Karachi: 24.86
Quetta: 30.18
Lahore: 31.55
Islamabad: 33.72
Peshawar: 34.01


---
# 📖 Section 4 — Dictionaries


## 📝 Task 10 — Dictionary Basics: Create, Access, Update

### Background
A dictionary stores data as **key → value** pairs. Keys must be unique and immutable (strings, numbers, tuples). Values can be anything. Key methods: `.keys()`, `.values()`, `.items()`, `.get()`, `.update()`, `.pop()`.

### 🎯 Your Task
Start with this student record:
```python
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}
```

1. Print Sara's **name** and **age**
2. Print her **list of courses**
3. Print her **CS grade** (access the nested dictionary)
4. Add a new key `"year"` with value `2`
5. Update her **age** to `21`
6. Remove the `"Physics"` grade from the nested `"grades"` dictionary using `.pop()`
7. Loop over all key-value pairs with `.items()` and print them line by line
8. Print a list of all **keys** and a list of all **values**

> 💡 **Hint:** Access nested dicts with chained brackets: `student["grades"]["CS"]`  
> 💡 **Hint:** `student.get("email", "Not found")` returns a default value if the key doesn't exist.


In [5]:
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}

# 1. Print name and age
print("Name:", student["name"])
print("Age:", student["age"])

# 2. Print list of courses
print("Courses:", student["courses"])

# 3. Print CS grade (nested access)
print("CS Grade:", student["grades"]["CS"])

# 4. Add "year": 2
student["year"] = 2
print("After adding year:", student["year"])

# 5. Update age to 21
student["age"] = 21
print("Updated age:", student["age"])

# 6. Remove "Physics" from grades using .pop()
removed_grade = student["grades"].pop("Physics")
print(f"Removed Physics grade: {removed_grade}")
print("Grades after removal:", student["grades"])

# 7. Loop and print all key-value pairs
print("\nAll key-value pairs:")
for key, value in student.items():
    print(f"{key}: {value}")

# 8. Print list of keys and list of values
print("\nKeys:", list(student.keys()))
print("Values:", list(student.values()))

Name: Sara
Age: 20
Courses: ['Math', 'Physics', 'CS']
CS Grade: 92
After adding year: 2
Updated age: 21
Removed Physics grade: 75
Grades after removal: {'Math': 88, 'CS': 92}

All key-value pairs:
name: Sara
age: 21
courses: ['Math', 'Physics', 'CS']
grades: {'Math': 88, 'CS': 92}
year: 2

Keys: ['name', 'age', 'courses', 'grades', 'year']
Values: ['Sara', 21, ['Math', 'Physics', 'CS'], {'Math': 88, 'CS': 92}, 2]


## 📝 Task 11 — Dictionary Comprehension & Word Frequency Counter

### Background
Just like list comprehensions, you can build dictionaries in one line:
```python
{key_expr: value_expr for item in iterable if condition}
```
Dictionaries are perfect for counting frequencies — a pattern you'll use constantly in data science.

### 🎯 Your Task

**Part A — Dictionary Comprehension:**
1. Create a dictionary mapping each number 1–10 to its **cube**: `{1: 1, 2: 8, 3: 27, ...}`
2. Create a dictionary mapping each number 1–20 to `"even"` or `"odd"`: `{1: 'odd', 2: 'even', ...}`

**Part B — Word Frequency Counter:**  
Count how many times each word appears in the text below, ignoring case. Print the result sorted by **frequency (descending)**.

```python
text = "to be or not to be that is the question to be is to think"
```
Expected top entries: `to: 4, be: 3, is: 2, ...`

> 💡 **Hint for Part B:** Start with `freq = {}`, then loop over `text.lower().split()`.  
> Use `freq[word] = freq.get(word, 0) + 1` to safely increment counts.  
> Sort with `sorted(freq.items(), key=lambda x: x[1], reverse=True)`.


In [6]:
# Part A — Dictionary comprehensions
# 1. Cubes of 1 to 10
cubes = {n: n**3 for n in range(1, 11)}
print("Cubes:", cubes)

# 2. Even/Odd mapping for 1 to 20
even_odd = {n: "even" if n % 2 == 0 else "odd" for n in range(1, 21)}
print("Even/Odd:", even_odd)


# Part B — Word frequency counter
text = "to be or not to be that is the question to be is to think"

# Create empty dictionary for frequencies
freq = {}

# Count words (case-insensitive)
for word in text.lower().split():
    freq[word] = freq.get(word, 0) + 1

# Sort by frequency (descending) and print
sorted_words = sorted(freq.items(), key=lambda x: x[1], reverse=True)

print("\nWord frequencies (sorted descending):")
for word, count in sorted_words:
    print(f"{word}: {count}")

Cubes: {1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}
Even/Odd: {1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd', 6: 'even', 7: 'odd', 8: 'even', 9: 'odd', 10: 'even', 11: 'odd', 12: 'even', 13: 'odd', 14: 'even', 15: 'odd', 16: 'even', 17: 'odd', 18: 'even', 19: 'odd', 20: 'even'}

Word frequencies (sorted descending):
to: 4
be: 3
is: 2
or: 1
not: 1
that: 1
the: 1
question: 1
think: 1


---
# 🔵 Section 5 — Sets


## 📝 Task 12 — Set Operations

### Background
A **set** is an **unordered collection of unique elements**. Duplicate values are automatically removed. Sets support mathematical operations: union (`|`), intersection (`&`), difference (`-`), symmetric difference (`^`).

| Operation | Symbol | Method | Meaning |
|-----------|--------|--------|---------|
| Union | `\|` | `.union()` | All elements from both sets |
| Intersection | `&` | `.intersection()` | Only elements in **both** |
| Difference | `-` | `.difference()` | Elements in A but **not** B |
| Symmetric Difference | `^` | `.symmetric_difference()` | Elements in either but **not both** |

### 🎯 Your Task
```python
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
```

1. Find students enrolled in **both** courses (intersection)
2. Find students enrolled in **at least one** course (union)
3. Find students taking **Python but NOT Java** (difference)
4. Find students taking **exactly one** course (symmetric difference)
5. Check if `{"Bob", "Alice"}` is a **subset** of `python_students`
6. Add `"Henry"` to `python_students` and remove `"Carol"` from it
7. Create a list `[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]` and use a set to print only the **unique values**

> 💡 **Hint:** Use `.issubset()` or the `<=` operator for subset check.


In [7]:
# Section 5 — Sets
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}

# 1. Intersection (students in both classes)
intersection = python_students.intersection(java_students)
print("Students in both classes:", intersection)
# Alternative: python_students & java_students

# 2. Union (all unique students)
union = python_students.union(java_students)
print("All unique students:", union)
# Alternative: python_students | java_students

# 3. Difference (Python but NOT Java)
only_python = python_students.difference(java_students)
print("Python only:", only_python)
# Alternative: python_students - java_students

# 4. Symmetric difference (in one but not both)
symmetric_diff = python_students.symmetric_difference(java_students)
print("In one but not both:", symmetric_diff)
# Alternative: python_students ^ java_students

# 5. Subset check: {"Bob", "Alice"} ⊆ python_students
subset = {"Bob", "Alice"}
is_subset = subset.issubset(python_students)
print(f"Is {subset} a subset of Python students? {is_subset}")
# Alternative: subset <= python_students

# 6. Add "Henry", remove "Carol"
python_students.add("Henry")
python_students.remove("Carol")
print("Python students after modifications:", python_students)

# 7. Unique values from list
nums = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
unique_nums = set(nums)
print("Unique values from list:", unique_nums)

Students in both classes: {'Bob', 'David', 'Alice'}
All unique students: {'David', 'Alice', 'Grace', 'Carol', 'Frank', 'Eve', 'Bob'}
Python only: {'Eve', 'Carol'}
In one but not both: {'Carol', 'Frank', 'Eve', 'Grace'}
Is {'Alice', 'Bob'} a subset of Python students? True
Python students after modifications: {'David', 'Henry', 'Alice', 'Eve', 'Bob'}
Unique values from list: {1, 2, 3, 4}


---
# 🔢 Section 6 — NumPy Arrays


## 📝 Task 13 — Creating & Inspecting NumPy Arrays

### Background
NumPy arrays are **fixed-type, multi-dimensional** arrays that support fast vectorised operations. Unlike Python lists, every element must be the same type. Key creation functions: `np.array()`, `np.arange()`, `np.linspace()`, `np.zeros()`, `np.ones()`, `np.eye()`, `np.random.random()`.

### 🎯 Your Task

Create each of the following arrays and print both the array and its `.shape` and `.dtype`:

| # | Function | Parameters | Expected shape |
|---|----------|------------|----------------|
| 1 | `np.arange` | 0 to 20, step 2 | `(11,)` |
| 2 | `np.linspace` | 0 to 1, 6 evenly spaced points | `(6,)` |
| 3 | `np.zeros` | 3 rows × 4 columns | `(3, 4)` |
| 4 | `np.ones` | 2 rows × 5 columns, dtype `int16` | `(2, 5)` |
| 5 | `np.eye` | 4×4 identity matrix | `(4, 4)` |
| 6 | `np.random.randint` | values 1–100, shape 3×3 | `(3, 3)` |

> 💡 **Hint:** `np.ones((2,5), dtype='int16')` creates an integer array of ones.  
> `np.random.randint(low, high, size=(r,c))` creates random integer arrays.


In [8]:
import numpy as np

# 1. arange: 0 to 20 step 2
arr1 = np.arange(0, 21, 2)
print("1. arange (0 to 20 step 2):")
print(arr1)
print("Shape:", arr1.shape, "| Data type:", arr1.dtype)
print()

# 2. linspace: 0 to 1 with 6 points
arr2 = np.linspace(0, 1, 6)
print("2. linspace (0 to 1, 6 points):")
print(arr2)
print("Shape:", arr2.shape, "| Data type:", arr2.dtype)
print()

# 3. zeros: 3x4
arr3 = np.zeros((3, 4))
print("3. zeros (3x4):")
print(arr3)
print("Shape:", arr3.shape, "| Data type:", arr3.dtype)
print()

# 4. ones: 2x5 dtype int16
arr4 = np.ones((2, 5), dtype='int16')
print("4. ones (2x5, int16):")
print(arr4)
print("Shape:", arr4.shape, "| Data type:", arr4.dtype)
print()

# 5. eye: 4x4 identity
arr5 = np.eye(4)
print("5. eye (4x4 identity):")
print(arr5)
print("Shape:", arr5.shape, "| Data type:", arr5.dtype)
print()

# 6. random integers 1-100, shape 3x3
arr6 = np.random.randint(1, 101, size=(3, 3))
print("6. random integers (1-100, 3x3):")
print(arr6)
print("Shape:", arr6.shape, "| Data type:", arr6.dtype)

1. arange (0 to 20 step 2):
[ 0  2  4  6  8 10 12 14 16 18 20]
Shape: (11,) | Data type: int64

2. linspace (0 to 1, 6 points):
[0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,) | Data type: float64

3. zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4) | Data type: float64

4. ones (2x5, int16):
[[1 1 1 1 1]
 [1 1 1 1 1]]
Shape: (2, 5) | Data type: int16

5. eye (4x4 identity):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4) | Data type: float64

6. random integers (1-100, 3x3):
[[ 17  11  57]
 [ 88  76  26]
 [ 97 100  58]]
Shape: (3, 3) | Data type: int32


## 📝 Task 14 — Array Indexing, Slicing & Reshaping

### Background
NumPy arrays use **row, column** indexing: `A[row, col]` or `A[row][col]`.  
Slicing: `A[r1:r2, c1:c2]` extracts a sub-array.  
`.reshape(rows, cols)` changes the shape without changing the data.  
`.T` gives the transpose.

### 🎯 Your Task
```python
A = np.arange(1, 26).reshape(5, 5)
```
This creates:
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
```

1. Print the **element at row 2, column 3** (value: 14)
2. Print the **entire third row** (index 2): `[11 12 13 14 15]`
3. Print the **entire second column** (index 1): `[ 2  7 12 17 22]`
4. Extract the **top-left 3×3 sub-matrix**: rows 0–2, columns 0–2
5. Extract the **bottom-right 2×2 sub-matrix**: last 2 rows and last 2 cols
6. Print the **transpose** of A (shape should become `(5,5)` but rows/cols swapped)
7. Reshape A into a 1D array of 25 elements, then into a shape `(25, 1)` column vector

> 💡 **Hint:** `A[:3, :3]` extracts the top-left corner. `A[-2:, -2:]` grabs the bottom-right corner.


In [9]:
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
print("Original matrix A:")
print(A)
print()

# 1. Element at row 2, col 3
print("1. Element at row 2, col 3:", A[2, 3])  # 14

# 2. Entire third row (index 2)
print("2. Entire third row:", A[2, :])  # [11 12 13 14 15]

# 3. Entire second column (index 1)
print("3. Entire second column:", A[:, 1])  # [ 2  7 12 17 22]

# 4. Top-left 3x3 sub-matrix
print("4. Top-left 3x3 sub-matrix:")
print(A[:3, :3])  # rows 0-2, columns 0-2

# 5. Bottom-right 2x2 sub-matrix
print("5. Bottom-right 2x2 sub-matrix:")
print(A[-2:, -2:])  # last 2 rows, last 2 columns

# 6. Transpose
print("6. Transpose of A:")
print(A.T)  # or np.transpose(A)

# 7. Reshape to 1D (25,) then to column vector (25,1)
print("7. Reshape operations:")
A_1d = A.reshape(25)
print("1D array (25,):", A_1d)
print("Shape:", A_1d.shape)

A_column = A.reshape(25, 1)
print("Column vector (25,1):")
print(A_column)
print("Shape:", A_column.shape)

Original matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

1. Element at row 2, col 3: 14
2. Entire third row: [11 12 13 14 15]
3. Entire second column: [ 2  7 12 17 22]
4. Top-left 3x3 sub-matrix:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
5. Bottom-right 2x2 sub-matrix:
[[19 20]
 [24 25]]
6. Transpose of A:
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
7. Reshape operations:
1D array (25,): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Shape: (25,)
Column vector (25,1):
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]
Shape: (25, 1)


## 📝 Task 15 — Vectorised Operations & Broadcasting

### Background
NumPy operations are applied **element-wise** to entire arrays without writing loops — this is called **vectorisation**. When arrays have compatible shapes, NumPy can **broadcast** smaller arrays across larger ones automatically.

### 🎯 Your Task

**Part A — Element-wise Operations:**
```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])
```
Compute and print (without loops):
1. `a + b`, `a - b`, `a * b`, `a / b`
2. Square root of `a` (use `np.sqrt`)
3. All elements of `a` greater than 25 (Boolean mask)
4. Use the Boolean mask to extract only elements of `a` greater than 25

**Part B — Matrix Operations:**
```python
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
```
5. Element-wise multiplication `M * N`
6. Matrix (dot) product `M @ N` or `np.dot(M, N)`
7. Sum of all elements, sum along each row, sum along each column

> 💡 **Hint for Boolean masking:** `mask = a > 25` creates `[False False False True True]`. Then `a[mask]` extracts `[40 50]`.  
> 💡 **Hint for axis sums:** `M.sum(axis=1)` sums each row; `M.sum(axis=0)` sums each column.


In [10]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])

# Part A
# 1. Element-wise +, -, *, /
print("1. Element-wise operations:")
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print()

# 2. Square root of a
print("2. Square root of a:")
print(np.sqrt(a))
print()

# 3. Boolean mask: elements of a > 25
mask = a > 25
print("3. Boolean mask (a > 25):")
print(mask)
print()

# 4. Extract elements > 25 using mask
print("4. Elements of a greater than 25:")
print(a[mask])
print()


# Part B
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])

# 5. Element-wise multiplication
print("5. Element-wise multiplication M * N:")
print(M * N)
print()

# 6. Matrix dot product
print("6. Matrix dot product M @ N:")
print(M @ N)  # or np.dot(M, N)
print()

# 7. Total sum, row sums, column sums
print("7. Sum operations:")
print(f"Total sum (all elements): {M.sum()}")
print(f"Sum along rows (axis=1): {M.sum(axis=1)}")
print(f"Sum along columns (axis=0): {M.sum(axis=0)}")

1. Element-wise operations:
a + b = [11 22 33 44 55]
a - b = [ 9 18 27 36 45]
a * b = [ 10  40  90 160 250]
a / b = [10. 10. 10. 10. 10.]

2. Square root of a:
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

3. Boolean mask (a > 25):
[False False  True  True  True]

4. Elements of a greater than 25:
[30 40 50]

5. Element-wise multiplication M * N:
[[ 5 12]
 [21 32]]

6. Matrix dot product M @ N:
[[19 22]
 [43 50]]

7. Sum operations:
Total sum (all elements): 10
Sum along rows (axis=1): [3 7]
Sum along columns (axis=0): [4 6]


---
# 🐼 Section 7 — Pandas DataFrames


## 📝 Task 16 — Creating & Exploring a DataFrame

### Background
A **DataFrame** is a 2D table with labelled rows (index) and columns. You can create one from a dictionary, a list of lists, a CSV file, or from scikit-learn datasets. Essential inspection methods: `.head()`, `.tail()`, `.info()`, `.describe()`, `.shape`, `.columns`, `.dtypes`, `.isnull().sum()`.

### 🎯 Your Task

**Part A — Create from a dictionary:**
```python
data = {
    "Name":    ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":     [23, 21, 25, 22, 24],
    "Score":   [88, 92, 78, 95, 83],
    "Passed":  [True, True, True, True, True],
    "City":    ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
```
1. Create a DataFrame from this dictionary
2. Print its **shape**, **column names**, and **data types**
3. Print the **first 3 rows** and the **last 2 rows**
4. Print **summary statistics** using `.describe()`

**Part B — Load the Iris dataset:**
5. Load the Iris dataset using `load_iris()` and add the species names
6. Print **how many rows belong to each species** using `.value_counts()`
7. Print the **mean of each numerical column grouped by species**

> 💡 **Hint for Iris:** `iris_df['species'] = iris.target_names[iris.target]` maps integer targets to names.  
> 💡 **Hint for groupby:** `iris_df.groupby('species').mean(numeric_only=True)`


In [11]:
import pandas as pd
from sklearn.datasets import load_iris

# Part A
data = {
    "Name":   ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":    [23, 21, 25, 22, 24],
    "Score":  [88, 92, 78, 95, 83],
    "Passed": [True, True, True, True, True],
    "City":   ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}

# 1. Create DataFrame
print("Part A - Student DataFrame:")
df = pd.DataFrame(data)
print(df)
print()

# 2. Print shape, columns, dtypes
print("DataFrame info:")
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print()

# 3. Head(3) and tail(2)
print("First 3 rows (head):")
print(df.head(3))
print("\nLast 2 rows (tail):")
print(df.tail(2))
print()

# 4. Describe
print("Summary statistics:")
print(df.describe(include='all'))
print()


# Part B — Iris
print("Part B - Iris Dataset:")
# 5. Load iris and create DataFrame
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

print("First 5 rows of Iris dataset:")
print(iris_df.head())
print()

# 6. Value counts per species
print("Count per species:")
print(iris_df['species'].value_counts())
print()

# 7. Mean per species
print("Mean of numerical columns by species:")
print(iris_df.groupby('species').mean(numeric_only=True))

Part A - Student DataFrame:
     Name  Age  Score  Passed       City
0     Ali   23     88    True     Lahore
1    Sara   21     92    True    Karachi
2    John   25     78    True     London
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York

DataFrame info:
Shape: (5, 5)
Columns: ['Name', 'Age', 'Score', 'Passed', 'City']
Data types:
Name        str
Age       int64
Score     int64
Passed     bool
City        str
dtype: object

First 3 rows (head):
   Name  Age  Score  Passed     City
0   Ali   23     88    True   Lahore
1  Sara   21     92    True  Karachi
2  John   25     78    True   London

Last 2 rows (tail):
     Name  Age  Score  Passed       City
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York

Summary statistics:
       Name        Age     Score Passed    City
count     5   5.000000   5.00000      5       5
unique    5        NaN       NaN      1       5
top     Ali        NaN       NaN   True  Lahore
freq      

## 📝 Task 17 — Selecting, Filtering & Adding Columns

### Background
- **Select columns:** `df['col']` (Series) or `df[['col1','col2']]` (DataFrame)
- **Select rows by position:** `df.iloc[start:stop]`
- **Select rows by label/condition:** `df.loc[condition]`
- **Add a column:** `df['new_col'] = expression`
- **Multiple conditions:** Use `&` (AND) or `|` (OR) — wrap each condition in `()`

### 🎯 Your Task
Use the **Iris DataFrame** from Task 16.

1. Select and print only the `sepal length (cm)` and `petal length (cm)` columns (first 5 rows)
2. Select rows **50 through 54** using `.iloc`
3. Filter rows where `species == 'versicolor'` and print how many there are
4. Filter rows where `petal length (cm) > 5.0` **AND** `species == 'virginica'`
5. Add a new column `"petal_area"` = `petal length (cm)` × `petal width (cm)` and print the first 5 rows
6. Sort the DataFrame by `petal_area` in **descending** order and print the top 5 rows

> 💡 **Hint:** `df[(df['col1'] > val) & (df['col2'] == 'label')]` — always wrap each condition in `()`.  
> 💡 **Hint:** `df.sort_values('petal_area', ascending=False).head(5)`


In [12]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

# 1. Select sepal length and petal length columns (head 5)
print("1. Sepal length and petal length (first 5 rows):")
print(iris_df[['sepal length (cm)', 'petal length (cm)']].head())
print()

# 2. Rows 50 through 54 using iloc
print("2. Rows 50 through 54:")
# iloc uses 0-based indexing, so row 50 is index 50
print(iris_df.iloc[50:55])
print()

# 3. Filter versicolor species, print count
versicolor_df = iris_df[iris_df['species'] == 'versicolor']
print(f"3. Number of versicolor samples: {len(versicolor_df)}")
# Alternative: versicolor_df = iris_df.loc[iris_df['species'] == 'versicolor']
print()

# 4. Filter: petal length > 5.0 AND species == 'virginica'
filtered_df = iris_df[(iris_df['petal length (cm)'] > 5.0) & (iris_df['species'] == 'virginica')]
print("4. Virginica samples with petal length > 5.0 cm:")
print(filtered_df)
print(f"Count: {len(filtered_df)}")
print()

# 5. Add petal_area column, print head
iris_df['petal_area'] = iris_df['petal length (cm)'] * iris_df['petal width (cm)']
print("5. First 5 rows with new 'petal_area' column:")
print(iris_df.head())
print()

# 6. Sort by petal_area descending, top 5
sorted_df = iris_df.sort_values('petal_area', ascending=False)
print("6. Top 5 rows sorted by petal_area (descending):")
print(sorted_df.head())

1. Sepal length and petal length (first 5 rows):
   sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4

2. Rows 50 through 54:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

       species  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
54  versicolor  

3. Number of versicolor samples: 50

4. Virginica samples with petal length > 5.0 cm:
     sepal length

## 📝 Task 18 — Capstone: Combined Data Structures Challenge

### Background
Real data science tasks require combining **all** the data structures you have learned. This final task tests your ability to choose the right structure for each job.

### 🎯 Your Task
You are given student records as a **list of dictionaries**:

```python
students = [
    {"name": "Alice",   "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",     "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",   "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",   "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",     "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",   "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",   "scores": [75, 80, 78], "city": "Lahore"},
]
```

Complete each of the following:

1. **Average score:** Add a key `"average"` to each student dict containing the average of their `scores` (round to 2 decimal places). Print all names and averages.

2. **Grade assignment:** Using a dictionary comprehension, create a dict `{name: grade}` where grade is:
   - `"A"` if average ≥ 85
   - `"B"` if average ≥ 70
   - `"C"` if average ≥ 55
   - `"F"` otherwise

3. **Top students:** Use a list comprehension to create a list of **names** of students with average ≥ 80.

4. **Unique cities:** Use a **set** to find all unique cities, then print them.

5. **NumPy statistics:** Convert all scores into a **2D NumPy array** (shape `7×3`). Compute and print:
   - Overall mean, min, max
   - Mean score per student (axis=1)
   - Mean score per test/column (axis=0)

6. **Pandas summary:** Create a **DataFrame** with columns `Name`, `Average`, `Grade`, `City`. Print it, then print the **average score per city** using `.groupby()`.

> 💡 **Hints:**
> - `sum(scores) / len(scores)` or `np.mean(scores)` for averages
> - `np.array([s["scores"] for s in students])` to build the 2D array
> - For the DataFrame, build a list of dicts or use parallel lists


In [13]:
import numpy as np
import pandas as pd

students = [
    {"name": "Alice",  "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",    "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",  "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",  "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",    "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",  "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",  "scores": [75, 80, 78], "city": "Lahore"},
]

# Step 1: Add "average" key to each student dict
print("Step 1 — Students with averages:")
for student in students:
    student["average"] = round(sum(student["scores"]) / len(student["scores"]), 2)
    print(f"{student['name']}: {student['average']}")
print()

# Step 2: Dict comprehension {name: grade}
def get_grade(avg):
    if avg >= 85:
        return "A"
    elif avg >= 70:
        return "B"
    elif avg >= 55:
        return "C"
    else:
        return "F"

grades = {student["name"]: get_grade(student["average"]) for student in students}
print("Step 2 — Grades:")
print(grades)
print()

# Step 3: List of names with average >= 80
top_students = [student["name"] for student in students if student["average"] >= 80]
print("Step 3 — Students with average >= 80:")
print(top_students)
print()

# Step 4: Set of unique cities
unique_cities = {student["city"] for student in students}
print("Step 4 — Unique cities:")
print(unique_cities)
print()

# Step 5: NumPy 2D array and statistics
scores_array = np.array([student["scores"] for student in students])
print("Step 5 — NumPy Statistics:")
print(f"Scores array shape: {scores_array.shape}")
print(f"Overall mean: {np.mean(scores_array):.2f}")
print(f"Overall min: {np.min(scores_array)}")
print(f"Overall max: {np.max(scores_array)}")
print(f"Mean per student (axis=1): {np.mean(scores_array, axis=1)}")
print(f"Mean per test (axis=0): {np.mean(scores_array, axis=0)}")
print()

# Step 6: Pandas DataFrame and groupby city
df_data = []
for student in students:
    df_data.append({
        "Name": student["name"],
        "Average": student["average"],
        "Grade": grades[student["name"]],
        "City": student["city"]
    })

df = pd.DataFrame(df_data)
print("Step 6 — Pandas DataFrame:")
print(df)
print()

print("Average score per city:")
city_avg = df.groupby("City")["Average"].mean().round(2)
print(city_avg)

Step 1 — Students with averages:
Alice: 84.33
Bob: 61.67
Carol: 91.67
David: 71.67
Eve: 50.0
Frank: 88.0
Grace: 77.67

Step 2 — Grades:
{'Alice': 'B', 'Bob': 'C', 'Carol': 'A', 'David': 'B', 'Eve': 'F', 'Frank': 'A', 'Grace': 'B'}

Step 3 — Students with average >= 80:
['Alice', 'Carol', 'Frank']

Step 4 — Unique cities:
{'Lahore', 'Islamabad', 'Karachi'}

Step 5 — NumPy Statistics:
Scores array shape: (7, 3)
Overall mean: 75.00
Overall min: 45
Overall max: 95
Mean per student (axis=1): [84.33333333 61.66666667 91.66666667 71.66666667 50.         88.
 77.66666667]
Mean per test (axis=0): [74.28571429 73.57142857 77.14285714]

Step 6 — Pandas DataFrame:
    Name  Average Grade       City
0  Alice    84.33     B     Lahore
1    Bob    61.67     C    Karachi
2  Carol    91.67     A  Islamabad
3  David    71.67     B     Lahore
4    Eve    50.00     F    Karachi
5  Frank    88.00     A  Islamabad
6  Grace    77.67     B     Lahore

Average score per city:
City
Islamabad    89.84
Karachi   

---
## 🤔 Reflection Questions

Answer the following as comments in the cell below:

1. What is the key difference between a **list** and a **tuple**? When would you prefer a tuple?
2. What is the key difference between a **list** and a **set**? Give one real-world use case for each.
3. Why can't a **list** be used as a dictionary key, but a **tuple** can?
4. In Task 15, what is the advantage of NumPy **vectorisation** over using a Python `for` loop?
5. In Task 17, why do we use `&` instead of `and` when filtering a Pandas DataFrame?
6. Looking at the Capstone (Task 18), which data structure did you find most useful? Why?


In [ ]:
# Q1: What is the key difference between a list and a tuple? When would you prefer a tuple?
# Lists are mutable (can be changed after creation), while tuples are immutable (cannot be changed).
# Tuples are preferred when:
# - Data should not be modified (e.g., coordinates, RGB values, constants)
# - Using as dictionary keys (since immutability is required)
# - They are slightly more memory efficient and faster to access
# - Representing fixed collections of related data (e.g., database records)

# Q2: What is the key difference between a list and a set? Give one real-world use case for each.
# Lists are ordered, allow duplicates, and support indexing. Sets are unordered, contain only unique elements, and don't support indexing.
# List use case: Storing student names in the order they submitted assignments (order matters, duplicates possible)
# Set use case: Finding all unique email addresses in a mailing list (automatic duplicate removal, membership testing)

# Q3: Why can't a list be used as a dictionary key, but a tuple can?
# Dictionary keys must be hashable (immutable). Lists are mutable, so their hash value could change if modified,
# making them unreliable as keys. Tuples are immutable, so their hash value remains constant.
# Python uses hash values to quickly locate dictionary entries; mutable keys could break this system.

# Q4: In Task 15, what is the advantage of NumPy vectorisation over using a Python for loop?
# Vectorisation is much faster because:
# - Operations are executed in C/Fortran (compiled code) rather than Python (interpreted)
# - No Python loop overhead (iteration, type checking, function calls)
# - Better CPU cache utilization
# - Enables parallel execution and SIMD (Single Instruction Multiple Data) operations
# For large datasets, vectorisation can be 10-100x faster than Python loops.

# Q5: In Task 17, why do we use & instead of and when filtering a Pandas DataFrame?
# & is the bitwise AND operator that Pandas overloads for element-wise boolean operations on Series.
# 'and' is a Python logical operator that works on single boolean values, not arrays.
# Each condition like df['col'] > 5 creates a boolean Series, and & combines them element-wise.
# Parentheses are required around each condition because & has higher precedence than comparison operators.

# Q6: Looking at the Capstone (Task 18), which data structure did you find most useful? Why?
# The pandas DataFrame was most useful because it:
# - Combines all student data into a single, readable table
# - Provides powerful built-in methods for analysis (.groupby(), .mean())
# - Handles different data types (strings, floats) seamlessly
# - Makes complex operations simple (like calculating city averages in one line)
# - Integrates well with other libraries for visualization and further analysis
# - Allows both row and column operations intuitively